matrix:
  ARCH:
    - linux/amd64

when:
  event: [push, tag, pull_request]
  branch: main

labels:
  platform: ${ARCH}

steps:
  build:
    image: opensuse/tumbleweed:latest
    commands:
      - zypper --non-interactive install rustup openssl-devel libzstd-devel
      - rustup default stable
      - rustup install nightly
      - rustup update
      - cargo update
      - cargo +nightly fmt -- --check
      - cargo clippy --tests
      - cargo test --release -- --test-threads=1

runs_on: [ success, failure ]
