matrix:
  ARCH:
    - linux/amd64

when:
  - event: [push, tag, pull_request]
    branch: [main]
    path:
      include: ['.woodpecker/*.yaml', '*.woodpecker/*.yml', "**/*.rs"]
      exclude: ['*.md', 'docs/**', '*.service', 'advocacy/**']

labels:
  platform: ${ARCH}

steps:
  build:
    image: opensuse/leap
    commands:
      - zypper --non-interactive install rustup openssl-devel libzstd-devel tar gzip
      - rustup default stable
      - rustup install nightly
      - rustup update
      - cargo update
      - cargo build

  release:
    image: opensuse/leap
    commands:
      - zypper --non-interactive install rustup openssl-devel libzstd-devel tar gzip
      - rustup default stable
      - rustup install nightly
      - rustup update
      - cargo update
      - cargo build --release

  tests:
    image: opensuse/leap
    commands:
      - zypper --non-interactive install rustup openssl-devel libzstd-devel tar gzip
      - rustup default stable
      - rustup install nightly
      - rustup update
      - cargo update
      - cargo test --release -- --test-threads=1
      - cargo test -F obs --test obs_scm --release -- --test-threads=1  # Tests are separated here because apparently, envs are shared between threads.

  style:
    image: opensuse/leap
    commands:
      - zypper --non-interactive install rustup openssl-devel libzstd-devel tar gzip
      - rustup default stable
      - rustup install nightly
      - rustup update
      - cargo update
      - cargo +nightly fmt -- --check
      - cargo clippy --tests

runs_on: [ success, failure ]
