name: Build Roast

on:
  push:
    paths:
      - '**.rs'
      - '**/Cargo.toml'
      - '!**.md'
  pull_request:
    paths:
      - '**.rs'
      - '**/Cargo.toml'
      - '!**.md'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container: opensuse/tumbleweed:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install dependencies and Rust
      run: |
        zypper --non-interactive in libzstd-devel rustup openssl-devel
        rustup default stable
        rustup update
    - name: Build
      run: |
        cargo update
        cargo build --release --all-features
    - name: Check formatting
      run: |
        cargo fmt -- --check || true
    - name: Check clippy
      run: |
        cargo clippy
        cargo clippy --tests
    - name: Run sample projects to test
      run: |
        cargo test --release -- --test-threads=1
